# 文档地址 https://docs.docker.com/compose/
# docker compose 协议地址：https://docs.docker.com/compose/compose-file/05-services/
# 启动 docker compose up -d
version: '3.9'
services:
  # 客户端
  client:
    image: visualddd/client:0.5.4-pre-free
    restart: always
    ports:
      - '3000:3000'
      # - '9229:9229' # DEBUG
    environment:
      # 更多设置：https://github.com/visual-ddd/visual-ddd-client/blob/main/DEVEPLOMENT.md
      SECRET: '请自行生成32位随机值'   # SESSION 密钥
      BACKEND: http://server:8080
      # AI_CONFIGURATION: '添加AI配置'
      # NODE_OPTIONS: NODEJS 配置项 # --inspect=0.0.0.0
      REDIS: redis://redis:6379/1
      DEFAULT_PLAN: free
      FREE_ACCOUNT_COUNT_LIMIT: 100
      HTTPS: false  # 默认关闭https

  # 多人协作服务器
  collab:
    image: visualddd/collab-server:latest
    ports:
      - '9090:9090'
    environment:
      MAIN_SERVER: http://client:3000

  # 后端服务
  server:
    image: visualddd/server:1.0.2-RC03
    restart: always
    ports:
      - '8080:8080'
    environment:
      common.mysql.url: jdbc:mysql://db:3306/wd_visual_ddd?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&autoReconnect=true
      common.mysql.username: root
      common.mysql.password: root
      # 注册邮箱域名限制，默认不开启
      register.mail.suffix-configs: wakedata.com
      register.whitelist.enable: 'false'
      # rabbitmq配置，默认不需要
      common.mq.message.default-type: rabbitMq
      common.mq.rabbitmq.bootstrap-servers: 172.26.57.49
      common.mq.rabbitmq.username: guest
      common.mq.rabbitmq.password: guest
      # email发邮件，设置发邮件的账号
      spring.mail.host: 'host'
      spring.mail.username: 'username'
      spring.mail.password: 'password'
      spring.mail.properties.mail.smtp.auth: 'false'
      spring.mail.properties.mail.smtp.starttls.enable: 'false'
      spring.mail.properties.mail.smtp.starttls.required: 'false'
      # 指定后端url地址，用于拼接密码重置路径
      password-reset.url.config: 'server.url'
    links:
      - mysql:db
    depends_on:
      - mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g

  # 数据库
  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/logs:/var/log
      - ./mysql/conf:/etc/mysql/conf.d
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  # redis
  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    command: --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
